package com.bernaferrari.sdkmonitor.ui.platform

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

/**
 * All user-facing copy for shared Compose UI.
 * Android supplies localized values via [ProvideSdkStrings]; other targets use [DefaultSdkStrings].
 */
data class SdkStrings(
    val apps: String = "Apps",
    val logs: String = "Logs",
    val settings: String = "Settings",
    val about: String = "About",
    val search: String = "Search",
    val searchApps: String = "Search apps",
    val clear: String = "Clear",
    val retry: String = "Retry",
    val refresh: String = "Refresh",
    val loading: String = "Loading",
    val error: String = "Error",
    val unknownError: String = "Unknown error",
    val appNotFound: String = "App not found",
    val allApps: String = "All apps",
    val userApps: String = "User apps",
    val systemApps: String = "System apps",
    val sortByName: String = "Name",
    val sortBySdk: String = "Target SDK",
    val noAppsFound: String = "No apps found",
    val noAppsSubtitle: String = "Try a different filter or search",
    val noLogsYet: String = "No change logs yet",
    val noLogsSubtitle: String = "SDK changes will appear here when apps update",
    val targetSdk: String = "Target SDK",
    val minSdk: String = "Min SDK",
    val version: String = "Version",
    val packageName: String = "Package",
    val lastUpdate: String = "Last update",
    val size: String = "Size",
    val permissions: String = "Permissions",
    val versionHistory: String = "Version history",
    val theme: String = "Theme",
    val themeSystem: String = "System",
    val themeSystemDescription: String = "Follow device setting",
    val themeMaterialYou: String = "Material You",
    val themeMaterialYouDescription: String = "Dynamic colors from wallpaper",
    val themeLight: String = "Light",
    val themeLightDescription: String = "Always light",
    val themeDark: String = "Dark",
    val themeDarkDescription: String = "Always dark",
    val backgroundSync: String = "Background sync",
    val backgroundSyncDescription: String = "Periodically refresh installed apps",
    val syncInterval: String = "Sync interval",
    val appFilter: String = "App filter",
    val analytics: String = "SDK analytics",
    val analyticsSection: String = "Analytics",
    val analyticsEmpty: String = "No analytics yet",
    val clearLogs: String = "Clear logs",
    val exportData: String = "Export data",
    val minutes: String = "Minutes",
    val hours: String = "Hours",
    val days: String = "Days",
    val cancel: String = "Cancel",
    val save: String = "Save",
    val justNow: String = "Just now",
    val systemApp: String = "System",
    val userApp: String = "User",
    val syncing: String = "Syncing apps…",
    val failedToLoadApps: String = "Failed to load apps",
    val failedToLoadLogs: String = "Failed to load logs",
    val settingsTitle: String = "Settings",
    val loadingSettings: String = "Loading settings…",
    val errorLoadingSettings: String = "Error loading settings",
    val appearance: String = "Appearance",
    val aboutSection: String = "About",
    val learnMoreAboutApp: String = "Learn more about this app",
    val tapToConfigureSync: String = "Tap to configure automatic updates",
    val notificationsRequired: String = "Notifications are required for background sync",
    val enabledDaily: String = "Enabled · daily updates",
    val enabledWeekly: String = "Enabled · weekly updates",
    val enabledMonthly: String = "Enabled · monthly updates",
    val enabledEvery: String = "Enabled · every",
    val notificationPermissionTitle: String = "Enable notifications",
    val notificationPermissionBody: String =
        "Allow notifications so SDK Monitor can alert you when an app changes its target SDK.",
    val allowNotifications: String = "Allow notifications",
    val notificationWarningTitle: String = "Notifications disabled",
    val notificationWarningBody: String =
        "Open system settings to enable notifications for background sync alerts.",
    val openSettings: String = "Open settings",
    val daily: String = "Daily",
    val weekly: String = "Weekly",
    val monthly: String = "Monthly",
    val custom: String = "Custom",
    val syncDialogTitle: String = "Background sync",
    val interval: String = "Interval",
    val enableSync: String = "Enable background sync",
    val singularMinute: String = "minute",
    val singularHour: String = "hour",
    val singularDay: String = "day",
    val pluralMinutes: String = "minutes",
    val pluralHours: String = "hours",
    val pluralDays: String = "days",
    val latest: String = "Latest",
    val appsCount: String = "apps",
    val noAnalyticsData: String = "No analytics data yet",
    val noAnalyticsSubtitle: String = "Sync apps first to see target SDK distribution",
    val privacy: String = "Privacy",
    val privacyBody: String =
        "SDK Monitor works fully offline. No account, no analytics, no network access required.",
    val openSource: String = "Open source",
    val getInTouch: String = "Get in touch",
    val viewOnGitHub: String = "View the source and contribute",
    val contactDescription: String = "Send feedback or ask questions",
    val noDataCollection: String = "No data collection",
    val exportDataDescription: String = "Download your app data as a CSV backup",
    val rateApp: String = "Rate on GitHub",
    val contact: String = "Contact",
    val madeWithLove: String = "Made with care for Android power users",
    val versionLabel: String = "Version",
    val updatedLabel: String = "Updated",
    val sizeLabel: String = "Size",
    val appInformation: String = "App info",
    val playStore: String = "Play Store",
    val appName: String = "SDK Monitor",
)

val DefaultSdkStrings = SdkStrings()

val LocalSdkStrings =
    staticCompositionLocalOf { DefaultSdkStrings }

@Composable
fun sdkStrings(): SdkStrings = LocalSdkStrings.current
