[versions]
activityCompose = "1.9.3"
androidGradlePlugin = "8.7.2"
appcompat = "1.7.0"
compose = "1.7.4"
constraintLayoutCompose = "1.0.1"
constraintLayout = "2.1.4"
coroutines = "1.9.0"
dagger = "2.52"
epoxy = "5.1.4"
fragment = "1.8.4"
glide = "4.16.0"
indicatorFastScroll = "1.4.0"
junit = "4.13.2"
kotlin = "2.0.21"
ktx = "1.13.1"
leakcanary = "2.14"
logger = "2.2.0"
lifecycle = "2.8.6"
material = "1.12.0"
materialDialogs = "3.3.0"
mavericks = "3.0.9"
mockitoCore = "5.14.1"
mockitoKotlin = "2.2.11"
navigation = "2.8.3"
notify = "1.4.0"
paging = "3.3.2"
paletteKtx = "1.0.0"
recyclerview = "1.3.2"
room = "2.6.1"
rxAndroid = "2.1.1"
rxJava = "2.2.21"
rxKotlin = "2.4.0"
rxRelay = "2.1.1"
rxkPrefs = "1.2.5"
stetho = "1.6.0"
timeago = "4.0.3"
viewModelCompose = "2.8.6"
work = "2.9.1"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayoutCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewModelCompose" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
androidx-paging-rxjava2 = { module = "androidx.paging:paging-rxjava2", version.ref = "paging" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "room" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-androidProcessor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger-androidSupport = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
epoxy = { module = "com.airbnb.android:epoxy", version.ref = "epoxy" }
epoxy-databinding = { module = "com.airbnb.android:epoxy-databinding", version.ref = "epoxy" }
epoxy-paging3 = { module = "com.airbnb.android:epoxy-paging3", version.ref = "epoxy" }
epoxy-processor = { module = "com.airbnb.android:epoxy-processor", version.ref = "epoxy" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
indicatorfastscroll = { module = "com.github.reddit:IndicatorFastScroll", version.ref = "indicatorFastScroll" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
leakcanary-support = { module = "com.squareup.leakcanary:leakcanary-support-fragment", version.ref = "leakcanary" }
logger = { module = "com.orhanobut:logger", version.ref = "logger" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-dialogs = { module = "com.afollestad.material-dialogs:core", version.ref = "materialDialogs" }
mavericks = { module = "com.airbnb.android:mavericks", version.ref = "mavericks" }
mavericks-rxjava2 = { module = "com.airbnb.android:mavericks-rxjava2", version.ref = "mavericks" }
mavericks-testing = { module = "com.airbnb.android:mavericks-testing", version.ref = "mavericks" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
notify = { module = "io.karn:notify", version.ref = "notify" }
stetho = { module = "com.facebook.stetho:stetho", version.ref = "stetho" }
rxjava2-rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxAndroid" }
rxjava2-rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxJava" }
rxjava2-rxkotlin = { module = "io.reactivex.rxjava2:rxkotlin", version.ref = "rxKotlin" }
rxkprefs = { module = "com.afollestad:rxkprefs", version.ref = "rxkPrefs" }
rxrelay = { module = "com.jakewharton.rxrelay2:rxrelay", version.ref = "rxRelay" }
timeago = { module = "com.github.marlonlom:timeago", version.ref = "timeago" }
